### ISSUE TITLE
Auth Validations

### ISSUE THREAD

**Issue by MTipps** [Nhlanhla-advocate/Horizon-e-commerce#25]
https://github.com/Nhlanhla-advocate/Horizon-e-commerce/blob/64d66fe3626b536b8836199e2fd2f2f1c9337e5c/server/src/controllers/authController.js#L7-L18

As we talked about, please move all validations into a separate folder. This will help with readability and also re-usability.

**Comment by Nhlanhla-advocate** [comment]
All done and ready for review
