### ISSUE TITLE
Two passwords

### ISSUE THREAD

**Issue by MTipps** [Nhlanhla-advocate/Horizon-e-commerce#27]
https://github.com/Nhlanhla-advocate/Horizon-e-commerce/blob/64d66fe3626b536b8836199e2fd2f2f1c9337e5c/server/src/models/admin.js#L4-L8

Assuming this is a mistake as you don't need two identical fields called `password`.

**Comment by Nhlanhla-advocate** [comment]
I deleted the duplicate password
